Assignment 3.1 all the py file and wheel file for installation
Nikhil-Govindam/mle-training pull request #15
Opened 2023-03-29 15:14 UTC by Nikhil-Govindam

**Assignment 3.1**

All the py file (ingest_data.py, train.py, score.py ) for Training the model
Readme Updated file for model setup 
environment file for environment setup
wheel file 
unit test 
functional test

2023-03-29 15:24 UTC, Nikhil-Govindam reviewed
Assignment 2.1

2023-03-29 15:24 UTC, Nikhil-Govindam commented on .gitignore
Assignment 2.1

2023-03-30 08:11 UTC, vinayksoni requested changes

2023-03-30 08:11 UTC, vinayksoni commented on ingest_data.py
> +def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
datatype

2023-03-30 08:11 UTC, vinayksoni commented on ingest_data.py
> +    # summary
doc strings

2023-03-30 08:11 UTC, vinayksoni commented on test_package.py
> +def test_pkg_installation():
have a separate folder for all the test files and add all checks...

2023-03-30 08:43 UTC, vinayksoni requested changes

2023-03-30 08:43 UTC, vinayksoni commented on test_file/ingest_data.py
> +def file_save():
py test should not deal with any paths.... once you package this and zip it .... it goes across different systems and different platforms.... and their installation of your packages will fail.

you can copy and create data set (can be a subset) here and then train your model and then get the results and verify the pipeline

2023-03-30 08:43 UTC, vinayksoni commented on test_file/score.py
> +housing = pd.read_csv("/home/nikhil_123/mle-training/housing.csv")
refer ingestion component

2023-03-30 09:58 UTC, vinayksoni requested changes

2023-03-30 09:58 UTC, vinayksoni commented on test_file/score.py
> +housing = pd.read_csv("/home/nikhil_123/mle-training/housing.csv")
don't use hard coded paths

2023-03-30 09:58 UTC, vinayksoni commented on test_file/train.py
> +housing = pd.read_csv("/home/nikhil_123/mle-training/housing.csv")
dont use hard coded path

2023-03-30 16:41 UTC, merged